services:
  db:
    image: postgres:15
    container_name: sandbrick-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres -c max_connections=250
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandbrick-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${SERVER_PORT}
      ACCESS_TOKEN_EXPIRATION_MINUTES: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
      REFRESH_TOKEN_EXPIRATION_DAYS: ${REFRESH_TOKEN_EXPIRATION_DAYS}
      APP_VALIDATION_FIRST_NAME_MIN_LENGTH: ${APP_VALIDATION_FIRST_NAME_MIN_LENGTH}
      APP_VALIDATION_FIRST_NAME_MAX_LENGTH: ${APP_VALIDATION_FIRST_NAME_MAX_LENGTH}
      APP_VALIDATION_LAST_NAME_MIN_LENGTH: ${APP_VALIDATION_LAST_NAME_MIN_LENGTH}
      APP_VALIDATION_LAST_NAME_MAX_LENGTH: ${APP_VALIDATION_LAST_NAME_MAX_LENGTH}
      APP_VALIDATION_PASSWORD_MIN_LENGTH: ${APP_VALIDATION_PASSWORD_MIN_LENGTH}
      APP_VALIDATION_PASSWORD_MAX_LENGTH: ${APP_VALIDATION_PASSWORD_MAX_LENGTH}
      APP_VALIDATION_AVATAR_MAX_SIZE: ${APP_VALIDATION_AVATAR_MAX_SIZE}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env.prod

volumes:
  postgres_data:
