version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    networks:
      - app-network

#  sandbrick:
#    image: sandbrick:0.1.0
#    container_name: sandbrick
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - SERVER_PORT=${SERVER_PORT}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
