server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/sbpdb_prod
    username: ${POSTGRES_USER:system}
    password: ${POSTGRES_PASSWORD:passw0rd}
    hikari:
      auto-commit: true
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
#    clean-disabled: true

  sql:
    init:
      mode: never

springdoc:
  packages-to-scan: com.sandbrick.sbp

logging:
  level:
    org.flywaydb.core: INFO
