spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    time-zone: UTC
  application:
    name: sandbrick
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 10
  jackson:
    time-zone: UTC
  config:
    import: optional:.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

app:
  validation:
    first-name-min-length: 3
    first-name-max-length: 255
    last-name-min-length: 3
    last-name-max-length: 255
    password-min-length: ${APP_VALIDATION_PASSWORD_MIN_LENGTH:6}
    password-max-length: 255
    avatar-max-size: ${APP_VALIDATION_AVATAR_MAX_SIZE:2097152}
  token:
    access-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES:15}
    refresh-days: ${REFRESH_TOKEN_EXPIRATION_DAYS:7}
