server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    time-zone: UTC
  application:
    name: sandbrick
  datasource:
    url: jdbc:postgresql://localhost:5432/sbpdb_dev
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: system
    password: passw0rd
    hikari:
      auto-commit: true
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
  jackson:
    time-zone: UTC
#  flyway:
#    enabled: true
#    locations: classpath:/db/migrations
springdoc:
  packages-to-scan: com.sandbrick.sbp
#  swagger-ui:
#    path: /api/v1/docs
#  api-docs:
#    path: /api/v1/docs/openapi.json
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
