server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/sbpdb_dev
    driver-class-name: org.postgresql.Driver
    username: system
    password: passw0rd
    hikari:
      auto-commit: true
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#  sql:
#    init:
#      mode: always
#      platform: postgres
#      data-locations: classpath:/db/data.sql
#      schema-locations: classpath:/db/schema.sql
  jackson:
    time-zone: UTC
#  flyway:
#    enabled: true
#    locations: classpath:/db/migrations
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
