server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sbpdb_dev}
    username: ${POSTGRES_USER:system}
    password: ${POSTGRES_PASSWORD:passw0rd}
    hikari:
      auto-commit: true
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false

springdoc:
  packages-to-scan: com.sandbrick.sbp
